language: bash

sudo: required

services: docker

env:
  global:
    - VERSION: "0.10.0"
    - BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
    - REPO: $DOCKER_USERNAME
    - TAG_MINOR: ${VERSION%.*}
    - TAG_MAJOR: ${VERSION%%.*}
    - GIT_REPO_LINK: "https://github.com/OlegGorj/bastion-image.git#dev-branch"
    - IMAGE: "bastion-image"
    - TAG: "latest"

branches:
  only:
    - master
    - /^(?i:deploy)-.*$/

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

before_install:
  - docker info
  - docker version
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - sudo apt-get update
  - sudo apt-get install git-all

install:
  - git --version
  - git clone https://github.com/OlegGorj/bastion-image.git
  - sudo mkdir /data
  - sudo mkdir /data/jenkins
  - sudo chown 1000 /data/jenkins
  - sudo docker build -t ${REPO}/${IMAGE}:${TAG} .
  - sudo docker image push ${REPO}/${IMAGE}:${TAG}
  - sudo docker image pull ${REPO}/${IMAGE}:${TAG}
